<template>
  <div id="app">
    <header>
      <nav>
        <ul>
          <li class="nav-item">
            <router-link class="nav-link" :to="{name:'Home'}" exact>
            <img class="logo" src="./assets/build-a-bot-logo.png" />
            Build-a-robot
            </router-link>
          </li>
          <li class="nav-item">
            <router-link class="nav-link" :to="{name:'Build'}" exact>
            Build
            </router-link>
          </li>
        </ul>
      </nav>
    </header>
    <div class="container">
    <aside class="aside">
      <router-view name="sidebar"/>
     </aside>
    <main>
      <!--<HomePage />-->
    
        <router-view/>
   
     
    </main>
    </div>
  </div>
</template>

<script>
//import HomePage from './home/HomePage.vue';
import RobotBuilder from './build/RobotBuilder.vue';

export default {
  name: 'app',
 
};
</script>
<style>
body{
  background: linear-gradient(to bottom,#555,#999);
  background-attachment: fixed;
}
</style>

<style scoped>/* below are styles for this App component*/
/*.robot-name*/

/*
.content >>> .robot-name 
.content /deep/ .robot-name {color:red;            
 border:2px solid blue;  
             }*/
             
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
}
main{
  
  padding:30px;
  background-color:white;
  width:964px;
  min-height:300px;
}
header {
  background-color:#999;
  width:1184px;
  margin:0 auto;
}
ul {
  padding:3 px;
  display:flex;
}
.nav-item {
  display: inline-block;
  padding: 5px 10px;
  font-size: 22px;
  border-right:1px solid #bbb;
}
.logo {
  vertical-align: middle;
  height: 30px;
}
.nav-link{
  text-decoration:none;
  color:inherit;
}

.router-link-active {
  color:white;
}
.container {
  display:flex;
  margin:10px auto 0 auto;
  justify-content:center;
}
.aside {
  padding:30px;
  background-color:#aaa;
  width:100px;
  min-height: 300px;
}

</style>
<!--

1.there is a Vue-specific webpack plugin being used to parse
this file into its individual parts and compile them in a way that a browser can use them
2.this component was passed into the Vue instance
so vue will work with what's generated by webpack to render
this component
3.App component is top component in our project
-->
