<template>
  <div id="app">
    Root Foo: {{rootFoo}} <br/>
    Robots Foo: {{robotsFoo}} <br/>
    Users Foo: {{usersFoo}} <br/>
    <br/>
    Root Getter Foo:{{rootGetterFoo}} <br/>
    Robots Getter Foo:{{robotsGetterFoo}}<br/>
    Users Getter Foo: {{usersGetterFoo}} <br/>
    <header>
      <nav>
        <ul>
          <li class="nav-item">
            <router-link class="nav-link" :to="{name:'Home'}" exact>
            <img class="logo" src="./assets/build-a-bot-logo.png" />
            Build-a-robot
            </router-link>
          </li>
          <li class="nav-item">
            <router-link class="nav-link" :to="{name:'Build'}" exact>
            Build
            </router-link>
          </li>
          <li class="nav-item cart">
            <router-link class="nav-link" :to="{name:'Cart'}" exact>
            Cart
            </router-link>
            <div class="cart-items">
               {{cart.length}}
            </div>
          </li>
        </ul>
      </nav>
    </header>
    <div class="container">
    <aside class="aside">
      <router-view name="sidebar"/>
     </aside>
    <main>
      <!--<HomePage />-->
    
        <router-view/>
   
     
    </main>
    </div>
  </div>
</template>

<script>
//import HomePage from './home/HomePage.vue';
import RobotBuilder from './build/RobotBuilder.vue';

export default {
  name: 'app',
  computed:{
    rootFoo(){
      return this.$store.state.foo;
    },
    robotsFoo(){
      return this.$store.state.robots.foo;
    },
    usersFoo(){
      return this.$store.state.users.foo;
    },
    rootGetterFoo(){
      return this.$store.getters.foo;
    },
    robotsGetterFoo(){
      return this.$store.getters['robots/foo'];
    },
    usersGetterFoo(){
      return this.$store.getters['users/foo'];
    },
    cart(){
      return this.$store.state.robots.cart;
    }
  } 
};
</script>
<style>
body{
  background: linear-gradient(to bottom,#555,#999);
  background-attachment: fixed;
}
</style>

<style scoped>/* below are styles for this App component*/
/*.robot-name*/

/*
.content >>> .robot-name 
.content /deep/ .robot-name {color:red;            
 border:2px solid blue;  
             }*/
             
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
}
main{
  
  padding:30px;
  background-color:white;
  width:964px;
  min-height:300px;
}
header {
  background-color:#999;
  width:1184px;
  margin:0 auto;
}
ul {
  padding:3 px;
  display:flex;
}
.nav-item {
  display: inline-block;
  padding: 5px 10px;
  font-size: 22px;
  border-right:1px solid #bbb;
}

.nav-item.cart {
  position:relative;
  margin-left:auto;
  border-right:none;
}

.logo {
  vertical-align: middle;
  height: 30px;
}
.nav-link{
  text-decoration:none;
  color:inherit;
}

.router-link-active {
  color:white;
}
.container {
  display:flex;
  margin:10px auto 0 auto;
  justify-content:center;
}
.aside {
  padding:30px;
  background-color:#aaa;
  width:100px;
  min-height: 300px;
}

.cart-items {
  position:absolute;
  top:-5px;
  right:-9px;
  font-size:18px;
  width:20px;
  text-align:center;
  display:inline-block;
  border-radius:100px;
  background-color:mediumseagreen;
}

</style>
<!--

1.there is a Vue-specific webpack plugin being used to parse
this file into its individual parts and compile them in a way that a browser can use them
2.this component was passed into the Vue instance
so vue will work with what's generated by webpack to render
this component
3.App component is top component in our project
-->
